# Generated by Django 4.1.2 on 2022-10-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0013_job_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vacancy',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
